/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'activeUsers' : bigint,
  'totalBottles' : bigint,
  'totalRewards' : bigint,
  'totalCarbonSaved' : number,
}
export interface Badge {
  'name' : string,
  'description' : string,
  'bottlesRequired' : bigint,
}
export type RecyclingStatus = { 'verified' : null };
export interface ScanRecord {
  'recyclingStatus' : RecyclingStatus,
  'bottleId' : string,
  'pointsEarned' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'totalBottlesRecycled' : bigint,
  'displayName' : string,
  'joinedAt' : Time,
  'rewardPoints' : bigint,
  'carbonSavedKg' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllScans' : ActorMethod<[], Array<[Principal, Array<ScanRecord>]>>,
  'getBadges' : ActorMethod<[], Array<Badge>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getScanHistory' : ActorMethod<[], Array<ScanRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitScan' : ActorMethod<[string], bigint>,
  'updateProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];