/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'totalBottles' : IDL.Nat,
  'totalRewards' : IDL.Nat,
  'totalCarbonSaved' : IDL.Float64,
});
export const RecyclingStatus = IDL.Variant({ 'verified' : IDL.Null });
export const Time = IDL.Int;
export const ScanRecord = IDL.Record({
  'recyclingStatus' : RecyclingStatus,
  'bottleId' : IDL.Text,
  'pointsEarned' : IDL.Nat,
  'timestamp' : Time,
});
export const Badge = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'bottlesRequired' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'totalBottlesRecycled' : IDL.Nat,
  'displayName' : IDL.Text,
  'joinedAt' : Time,
  'rewardPoints' : IDL.Nat,
  'carbonSavedKg' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllScans' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ScanRecord)))],
      ['query'],
    ),
  'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScan' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'updateProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'totalBottles' : IDL.Nat,
    'totalRewards' : IDL.Nat,
    'totalCarbonSaved' : IDL.Float64,
  });
  const RecyclingStatus = IDL.Variant({ 'verified' : IDL.Null });
  const Time = IDL.Int;
  const ScanRecord = IDL.Record({
    'recyclingStatus' : RecyclingStatus,
    'bottleId' : IDL.Text,
    'pointsEarned' : IDL.Nat,
    'timestamp' : Time,
  });
  const Badge = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'bottlesRequired' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'totalBottlesRecycled' : IDL.Nat,
    'displayName' : IDL.Text,
    'joinedAt' : Time,
    'rewardPoints' : IDL.Nat,
    'carbonSavedKg' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllScans' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ScanRecord)))],
        ['query'],
      ),
    'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScan' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'updateProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };